export const toWardrobeItemDto = (item) => ({
  id: item.id,
  name: item.name,
  description: item.description,
  notes: item.description,
  imageUrl: item.imageUrl,
  category: item.category,
  subCategory: item.subCategory,
  primaryColor: item.primaryColor,
  colors: item.colors,
  brand: item.brand,
  size: item.size,
  material: item.material,
  season: item.season,
  occasion: item.occasion,
  tags: item.tags,
  isFavorite: item.isFavorite,
  isArchived: item.isArchived,
  createdAt: item.createdAt,
  updatedAt: item.updatedAt,
});
